version: "3.7"

services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
      - 7900:7900 
    shm_size: 2gb
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"

  selenium-edge:
    image: selenium/standalone-edge:latest
    ports:
      - 4445:4444 
      - 7901:7900 
    shm_size: 2gb
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"

  selenium-firefox:
    image: selenium/standalone-firefox:latest
    ports:
      - 4446:4444 
      - 7902:7900 
    shm_size: 2gb
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"

  db:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ubyssey
      MYSQL_DATABASE: ubyssey
    ports:
      - "3307:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=ubyssey --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 20
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"

  django:
    image: ubyssey/ubyssey.ca:latest
    volumes:
      - ..:/app/mount
      - .:/app/tmp
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
    depends_on:
      - db
    stdin_open: true
    tty: true
    links:
      - selenium-chrome
      - selenium-edge 
      - selenium-firefox
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"

  cache:
    platform: linux/x86_64
    image: memcached:1.6.10
    ports:
      - "11211:11211"
    depends_on:
      - django
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"

volumes:
  database:
    external:
      name: ubyssey_db_volume
